# ---------------------------------- #
# +--------------------------------+
# |       Trey's Double Jump       |
# | An amazing double jump plugin! |
# |         (c): TreyRuffy         |
# +--------------------------------+
# ---------------------------------- #
# ------------------------------------------------------------------------------------- #
# +-----------------------------------------------------------------------------------+
# | Permissions:                                                                      |
# |  tdj.*         - Gives all the permissions to a player                            |
# |  tdj.command   - Allows you to use the /tdj command                               |
# |  tdj.use       - Allows you to use the double jump feature                        |
# |  tdj.sounds    - Allows you to hear sounds whilst double jumping                  |
# |  tdj.particles - Allows you to summon particles whilst double jumping             |
# +-----------------------------------------------------------------------------------+
# ------------------------------------------------------------------------------------- #
Messages:
  ToggledOff: '&6You have &c&ldisabled &6your double jump!'
  # Disabled message
  FlyToggledOff: '&6You have &c&ldisabled&6 your flight!'
  # Disabled message for fly
  GroundPoundToggledOff: '&6You have &c&ldisabled&6 your ground pound!'
  # Disabled message for ground pound
  ToggledOn: '&6You have &a&lenabled &6your double jump!'
  # Enabled message
  FlyToggledOn: '&6You have &a&lenabled&6 your flight!'
  # Enabled message for fly
  GroundPoundToggledOn: '&6You have &a&lenabled&6 your ground pound!'
  # Enabled message for ground pound
  PlayersOnly: '&cYou must be a player to execute this command.'
  # Saying only players can execute the command
  NoPermission: '&cYou do not have permission to execute this command.'
  # No permissions for the command.
  FlyCommandDisabled: '&dThe fly command is disabled'
  # If Flight is disabled below, you will receive this message
  NotInWorld: '&cYou cannot do that in this world.'
  # If the player is not in one of the listed worlds below and tried to execute a command.
  PlayerNotFound: '&c[user] is not online.'
  # Sent if the player is not online
  ToggledOnOther: '&6You have &a&lenabled &6double jump for [user]!'
  # Message sent if you enable double jump for another player
  ToggledOffOther: '&6You have &c&ldisabled &6double jump for [user]!'
  # Message sent if you disable double jump for another player
  InvalidArgument: '&cInvalid argument: Please do /tdj [enable/disable]'
  # Message sent if you have invalid arguments
  InvalidArgumentConsole: '&cInvalid argument: Please do /tdj <username> [enable/disable]'
  # Message sent if console has invalid arguments
  InvalidArgumentWithOther: '&cInvalid argument: Please do /tdj [username] [enable/disable]'
  # Message sent if you have invalid arguments with permission to set another players double jump
  InvalidFlyArgument: '&cInvalid argument: Please do /fly [enable/disable]'
  # Message sent if you have invalid arguments for the flight command
  InvalidFlyArgumentConsole: '&cInvalid argument: Please do /fly <username> [enable/disable]'
  # Message sent if console has invalid arguments for the flight command
  InvalidFlyArgumentWithOther: '&cInvalid argument: Please do /fly [username] [enable/disable]'
  # Message sent if you have invalid arguments with permission to set another players flight
  FlyToggledOnOther: '&6You have &a&lenabled &6flight for [user]!'
  # Message sent if you enable flight for another player
  FlyToggledOffOther: '&6You have &c&ldisabled &6flight for [user]!'
  # Message sent if you disable flight for another player
  FlightToggledOn: '&6Your flight has been &a&lenabled&6!'
  # Message sent when another player enables your flight
  FlightToggledOff: '&6Your flight has been &c&ldisabled&6!'
  # Message sent when another player disables your flight
  DoubleJumpToggledOn: '&6Your double jump has been &a&lenabled&6!'
  # Message sent when another player enables your double jump
  DoubleJumpToggledOff: '&6Your double jump has been &c&ldisabled&6!'
  # Message sent when another player disables your double jump
Flight:
  Enabled: true
  # Allows you to enable /fly
NoFall:
  Enabled: true
  # Do you want to have no fall damage for everyone with tdj.nofall?
Cooldown:
  Enabled: false
  Time: 3
InfiniteJump:
  Enabled: false
  # If this is enabled, the player does not need to be on the ground to double jump.
  # Turn off the cooldown to infinitely double jump.
Velocity:
  Forward: 1.6
  # Allows you to set the forward jump velocity
  Up: 1
  # Allows you to set the upward jump velocity
  SprintingForward: 1.8
  # Allows you to set the forward jump velocity while sprinting
  SprintingUp: 1.2
  # Allows you to set the upward jump velocity while sprinting
Sounds:
  Enabled: true
  # Do you want players with tdj.sounds to play sounds when double jumping?
  Type: ENTITY_BAT_TAKEOFF
  # The type of sound played if the above option is true
  Volume: 1.0
  # The volume of the sound
  Pitch: 1.0
  # The pitch of the sound
Particles:
  Enabled: true
  # Do you want players with tdj.particles to summon particles when double jumping?
  Type: EXPLOSION_NORMAL
  # The type of particle played if the above option is true
  AllPlayers: true
  # Do you want all players to see the player's particles when double jumping?
  Amount: 5
  # The amount of particles you want it to summon, if particles are enabled
  # #If DUST particles are used, you can set the RGB values using R G B!#
  R: 0
  #Red value. (Leave as 0 if you are not using DUST particles)
  G: 0
  #Green value. (Leave as 0 if you are not using DUST particles)
  B: 0
  #Blue value. (Leave as 0 if you are not using DUST particles)
GroundPound:
  Enabled: true
  # Do you want players to be able to ground pound with tdj.groundpound
  VelocityDown: 4
  # What velocity do you want the groundpound to use?
EnabledWorlds:
  - world
  - world_the_end
  - world_nether
  # The worlds you want double jumping and no fall damage enabled in
DisabledBlocks: [ ]
# Blocks to disable the double jump, if standing on

BedrockPlayerPrefix: "." # Character that is added before a player's username via Geyser.
